export const surpriseMePrompts = [
  'un fauteuil en forme davocat',
  'une peinture à lhuile surréaliste de Salvador Dalí représentant un chat jouant aux échecs',
  'des ours en peluche faisant leurs courses au Japon, ukiyo-e',
  'une peinture à lhuile de Matisse représentant un robot humanoïde jouant aux échecs',
  'un panda savant fou mélangeant des produits chimiques scintillants, art numérique',
  'une photographie macro de deux souris à Hawaï, portant chacune un petit maillot de bain et une petite planche de surf, art numérique',
  'rendu 3D dun joli poisson tropical dans un aquarium sur un fond bleu foncé, art numérique',
  'un astronaute se prélassant dans une station balnéaire tropicale dans lespace, vaporwave',
  'un portrait à lhuile dun capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre',
  'une fenêtre en vitrail représentant un hamburger et des frites',
  'un dessin à la mine de plomb et à laquarelle dune ville lumineuse du futur avec des voitures volantes',
  'un coin salon intérieur ensoleillé avec une piscine deau claire et une autre piscine deau rose translucide, à côté dune grande fenêtre, art numérique',
  'un shiba inu qui prédit votre destin dans un hamburger géant, art numérique',
  '"une loutre de mer avec une boucle doreille en perle par Johannes Vermeer',
  'un dessin aux pastels gras dun chat agacé dans un vaisseau spatial',
  'un tableau dun renard dans le style de La nuit étoilée',
  'un bol de soupe qui ressemble à un monstre, tricoté en laine',
  'un robot en peluche assis contre un mur jaune',
  'un coucher de soleil style synthwave au-dessus de leau réfléchissante de la mer, art numérique',
  'deux tours futuristes avec un pont couvert de feuillage luxuriant, art numérique',
  'un ballon à air chaud multicolore en 3D volant au-dessus dun lac réfléchissant',
  'une couverture de bande dessinée dun super-héros portant des écouteurs',
  'une explosion colorée centrée sur un fond noir',
  'une photo dun chien Samoyède avec sa langue qui pend en train de câliner un chat siamois blanc',
  'une photo dun monstre de fourrure blanche debout dans une pièce violette',
  'une photo de la sculpture de David de Michel-Ange portant des écouteurs en train de mixer',
  'un samouraï chevauchant un cheval sur Mars, lomography',
  'une Cadillac moderne et élégante roulant le long de lautoroute Gardiner avec le centre-ville de Toronto en arrière-plan, avec un flare, photographie 50mm',
  'une photographie réaliste dune jeune femme aux yeux bleus et aux cheveux blonds',
];
